version: "3.9" 
services:
  loki:
    build: .
    ports:
      - "8080:8085"
    command: ["./gradlew", "flywayMigrate", "test", "--no-daemon"]
    volumes:
      - ".:/home/app/"
    depends_on:
      - "db"
    env_file:
      - '.env.test'

  db: 
    image: postgres:14.2-alpine3.15
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - '.env.test'

  kafka:
    image: bitnami/kafka:2.8.1
    restart: unless-stopped
    ports:
    - "29092:29092"
    env_file:
      - '.env.test'
    depends_on:
      - zookeeper
  
  zookeeper:
    image: zookeeper:3.8.0
    hostname: zookeeper
    ports:
    - "2181:2181"
    env_file:
      - '.env.test'

